### ISSUE TITLE
Android Q Webview

### ISSUE THREAD

**Issue by dimqua** [wchen342/ungoogled-chromium-android#10]
Is it possible to install your webview version on Android 10 (LOS 17, in particular)? The [old tricks](https://github.com/bromite/bromite/wiki/Installing-SystemWebView) don't work for me anymore: the app is installed, but I can't choose (enable) it.

It seems the package name is [not a problem](https://privatebin.net/?546989aa8e2dec08#3naW54nrYaE9ySikKAMZubvSWdxf1kCTHvhbcFvY7Css):
```
A: description="AOSP WebView" (Raw: "AOSP WebView") A: packageName="com.android.webview" (Raw: "com.android.webview")
```
Google Webview works, though. The same problem with Bromite System Webview.

**Comment by wchen342** [comment]
If Bromite has the same problem then it must be sth changed with the system. @csagan5 Do you know anything about this?

**Comment by csagan5** [comment]
@wchen342 I do not have direct experience with Android 10; what is written on the wiki still applies: https://github.com/bromite/bromite/wiki/Installing-SystemWebView

There is no trick: first one has to verify what `framework-res.apk` allows, as explained there.

If your `framework-res.apk` does not allow a custom webview then you cannot install any without root.

If something has changed with Android 10 in this regard I would like the wiki page to be updated, but probably the best source of information are ROM modders/maintainers on XDA.

**Comment by wchen342** [comment]
I do not have a physical machine that can be updated to Android 10, and emulator version actually has a development setting which is different from actual machines, so unfortunately I cannot test it right now. I will try to see what other information I can find on this.

**Comment by csagan5** [comment]
@wchen342 you could ask here about the rationale: https://github.com/GrapheneOS/Vanadium/issues/43

**Comment by ghost** [comment]
https://groups.google.com/a/chromium.org/forum/m/#!topic/android-webview-dev/Y8FIRqJCCNA

**Comment by wchen342** [comment]
@0xthoroughbred Thanks for the information. I will close this for now since it is an upstream problem. Feel free to reopen/open a new issue if this still happens after they added the support for WebView.

**Comment by csagan5** [comment]
I have added this link to [Bromite's wiki page about the SystemWebView](https://github.com/bromite/bromite/wiki/Installing-SystemWebView).
