### ISSUE TITLE
min sdk

### ISSUE THREAD

**Issue by DI555** [wchen342/ungoogled-chromium-android#12]
Please take down min sdk to 19 (android 4.4)!
Or if not possible to do so, just please take it to min sdk 21 (android 5.0), it has a huge amount of devices yet.
Thank you a lot in advance!!!

**Comment by wchen342** [comment]
See the [new release](https://github.com/wchen342/ungoogled-chromium-android/releases/tag/79.0.3945.117-2). Please report back if there are any bugs.

**Comment by DI555** [comment]
it's almost all working....
i've found just unworkable ui flags keys..., and some keys are working, some not(((... :

**Comment by wchen342** [comment]
That is probably be a problem accross all Android versions, not just low API ones. Can you elaborate which ones are not working so I can look into them?

**Comment by DI555** [comment]
i'm testing now armV7 build, about arm64 will tell  lately....
upd
wow it's great,- after another relaunching all became working, but doh ui in 'setting'/'personal data' still not appeared:
#dns-over-https              - not working

is it min sdk 19 ? if lower as i know could be some little bugs....
but from min sdk 19 all should be working fine!

**Comment by wchen342** [comment]
Please see [this section](https://github.com/wchen342/ungoogled-chromium-android#platforms-and-versions) for relationships between platforms and apk names.

> but doh ui in 'setting'/'personal data' still not appeared

I think there is no setting screen for that. You need to set your dns server from the system. Also this function is not currently working in ungoogled-chromium I believe. There is a patch from Bromite I may port in the future.

**Comment by DI555** [comment]
wow, great! thank you for descriptions of builds!
i'll close this issue after arm64 testing!

yes, i saw that doh menu there ..., but i thought it's from chromium team...( ....so, when i turn on doh flag it just use google doh servers and it's it!? 
...so, logically, if we're ungoogled ;), that bromite doh patch with 'Secure DNS' ui in settings is highly needed indeed!!!

**Comment by DI555** [comment]
64 bits verson works fine!
so, will wait for Secure DNS patch!
interesting, could it be modyfied to use also and DoT like it uses now DoH... ?
or it's deeper in the chromium core...

**Comment by wchen342** [comment]
@DI555 DoT is supposed to be done on system level, which Android has since Pie. Please [read this](https://blog.cloudflare.com/enable-private-dns-with-1-1-1-1-on-android-9-pie/) if you want to know how to set it. DoH is more like a hack that serves as a temporary solution offered by browsers.
