### ISSUE TITLE
Videos crash after about a second of playback

### ISSUE THREAD

**Issue by Poomex** [wchen342/ungoogled-chromium-android#15]
Since the last release every video I try to play crashes with the message "Ungoogled Chromium keeps stopping". 
I'm using the arm64 version on my Xiaomi Redmi Note 7 with LineageOS.

**Comment by wchen342** [comment]
Can you post the log when it crashes so that I can know the cause of the crash?

Also please try uninstall and resintall because the last version fixed a previous undiscovered problem in settings which could cause strange behaviors.

**Comment by Poomex** [comment]
Unfortunately, reinstalling didn't solve the issue. 

Would you mind telling me where to find the logs?

**Comment by Poomex** [comment]
Unfortunately, reinstalling didn't help. 
The logs are attached (there are some errors in chromium at the end) 
[logcat_02-26-2020_23-37-48.txt](https://github.com/wchen342/ungoogled-chromium-android/files/4258541/logcat_02-26-2020_23-37-48.txt)

**Comment by wchen342** [comment]
It looks like a codec/hardware acceleration problem to me. Can you report back the following:
1. Try to open the video in genuine chromium [here](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Android%2F722276%2Fchrome-android.zip?generation=1575590219192209&alt=media) and see whether it crashes.
2. Post a video link so I can see whether it crashes on my phone too?

EDIT: I think it is a known issue which has already been reported upstream: [https://bugs.chromium.org/p/chromium/issues/detail?id=977583](https://bugs.chromium.org/p/chromium/issues/detail?id=977583). I will release a new version shortly migrating another critical security issue from Google and I will include a patch that can (probably) fix this issue.

**Comment by Poomex** [comment]
This happens with every video, but I tested it with this link:

https://m.youtube.com/watch?v=wFF9O73iwko

It works in the vanilla version of chromium.

**Comment by wchen342** [comment]
Should be fixed in c170aefeec7212f6545f736011401967afa38235.

**Comment by Poomex** [comment]
Issue has returned in the newest release.

**Comment by wchen342** [comment]
Addtional fix added in [new version](https://github.com/wchen342/ungoogled-chromium-android/releases/tag/81.0.4044.129-1).
