### ISSUE TITLE
How to generate signed apk ?

### ISSUE THREAD

**Issue by karanSignity** [wchen342/ungoogled-chromium-android#17]
I have seen your patches, it looks very useful for me. I'm also working on chromium but I'm facing one issue please tell me how can I generate a signed Apk with my own Keystore. Also, please assist me in which files do I need to modify to generate signed Apk with my own Keystore or can you create a patch for this.

**Comment by wchen342** [comment]
The apk is already signed by its own key. Why do you want a different signing key for it?

**Comment by karanSignity** [comment]
@wchen342, Yes I know it is already signed by debug certificates "chromium-debug. keystore" but I want to create release Apk with my own certificate. Which I can upload on the play store. I am attaching below screenshots of which contains the path of debug keystore.

![config_gni](https://user-images.githubusercontent.com/59385421/76616928-27a07080-654b-11ea-982e-0e97960c8a39.png)
![Keystore](https://user-images.githubusercontent.com/59385421/76616935-296a3400-654b-11ea-9ffe-3ab1d877d92b.png)

**Comment by wchen342** [comment]
Can you try adding `default_android_keystore_path="{path to your keystore file}"` in `gn` flags file and build? I think that will be the most straightforward way.
