### ISSUE TITLE
Searx.me is no more 

### ISSUE THREAD

**Issue by Madis0** [wchen342/ungoogled-chromium-android#19]
Searx.me is no longer a Searx instance. Since [the instances](https://searx.space/)  may change at any time anyway, perhaps you could add Qwant instead?

**Comment by wchen342** [comment]
Thanks for the report. `searx` is added upstream so I will file an issue there. Meanwhile I will add `Qwant` in next version.

**Comment by wchen342** [comment]
Qwant is added in ff3bc4a.

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/19](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/19)
