### ISSUE TITLE
Same package name as usual Chromium

### ISSUE THREAD

**Issue by TotalCaesar659** [wchen342/ungoogled-chromium-android#2]
Hello, could you change the package name org.chromium.chrome to org.ungoogled.chromium or something like this? It's overwritten usual Chromium when installing.

**Comment by wchen342** [comment]
This will need some work since a change of the package name means any reference in the code also needs to be changed. I will try to look into this when I have time.

At the mean time, is there are specific reason you want to install two chromium versions side by side?

**Comment by TotalCaesar659** [comment]
Well, I knew it from [here](https://github.com/Eloston/ungoogled-chromium/issues/56) and wanted to test the behaviour of both versions, but I can't cause of it. I was unpleasantly surprised cause desktop ungoogled-chromium has many distributions that don't touch usual Chromium.
And it should make developers' work easier for testing, even so little thing would be great.

**Comment by wchen342** [comment]
It should be fixed in [new version](https://github.com/wchen342/ungoogled-chromium-android/releases/tag/75.0.3770.100-1). Please let me know if you encounter any bug because of the change.

**Comment by TotalCaesar659** [comment]
Both apps can be installed and work simultaneously. LGTM for now.
