### ISSUE TITLE
Permission prompt on first launch

### ISSUE THREAD

**Issue by Madis0** [wchen342/ungoogled-chromium-android#20]
![Screenshot](https://user-images.githubusercontent.com/8611110/82632379-b6db9b80-9c00-11ea-8bd0-2f673f9ed685.jpg)

I did not test what actually happens when clicking either notification, but it is confusing nonetheless, as Google sync should be removed.

**Comment by wchen342** [comment]
I don't see what permissions are required from your screenshots so I cannot tell whether that's normal or not. Usually `chromium` needs certain permissions to function which declared in the apk.

EDIT: how did you determine they are Google sync related? I have never seen such notifications.

**Comment by Madis0** [comment]
I believe it is the Google Play Services account request, as I've seen it on other Chromium-based browsers too.

**Comment by wchen342** [comment]
See my edited comment above. Also what version is you OS?

**Comment by Madis0** [comment]
Android 10. This is how it looks like when tapped (blacked out is the email address):

![Screenshot_20200522-080508](https://user-images.githubusercontent.com/8611110/82633167-205ca980-9c03-11ea-8e05-1b80cefa4433.jpg)

**Comment by wchen342** [comment]
Must be some new functions in Android 10. I don't have a physical phone that runs 10 but I will try to dig this on a virtual machine.

**Comment by Madis0** [comment]
Pretty sure I've seen it from Android 8 though. Does your device have Google Play Services installed?

**Comment by wchen342** [comment]
I have an Android 8 phone with Google Play but I didn't see this when I tested. Actually I have never seen that request at all.

**Comment by eklavya002** [comment]
I have also seen this ,it is sync function that is triggering . I have seen it on bromite previously may be dev has managed to omit the function.  chromium browser also triggers that.

**Comment by eklavya002** [comment]
one year back there was also problem with brave they have omitted the account permission.
![Screenshot_20200522-110215](https://user-images.githubusercontent.com/61374684/82634721-257a2280-9c1c-11ea-8f96-a79a8271ab4e.png)

**Comment by eklavya002** [comment]
bromite release after nochromo patch
![Screenshot_20200522-111150](https://user-images.githubusercontent.com/61374684/82635158-3e370800-9c1d-11ea-8ea2-d7b69fa21400.png)

**Comment by Madis0** [comment]
@eklavya002 Off-topic, but where did you get Brave Nightly for Android? The official page says it's not available: https://brave.com/download-nightly/

**Comment by eklavya002** [comment]
> @eklavya002 Off-topic, but where did you get Brave Nightly for Android? The official page says it's not available: https://brave.com/download-nightly

https://github.com/brave/brave-browser/releases 
checkout only nightly channel not desktop nightly

**Comment by wchen342** [comment]
@eklavya002 the GCM libraries are completely removed in my builds so there should be nothing actually happening. I have found the Bromite issue mentioning this and will try to patch this out.

**Comment by wchen342** [comment]
Fixed by ff3bc4a.
