### ISSUE TITLE
Consider eliding the protocol

### ISSUE THREAD

**Issue by Madis0** [wchen342/ungoogled-chromium-android#21]
I couldn't find which patch actually did this here, so am writing a request instead.

Please, consider hiding the protocol of the URL:

- it doesn't give the full picture (e.g. broken https, localhost http) unlike the security state icon
- it is mostly redundant (most connections are secure nowadays)
- the https display is inconsistent (on host-only sites it's black, with a path it's green, with a colored background it's gray)
- [it is better to highlight insecure sites overall](https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure), rather than highlight the secure sites

See also: https://github.com/bromite/bromite/issues/193.

Some related flags to consider default-enabling instead:

- `#enable-mark-http-as` - Enabled (mark as actively dangerous)
- `#passive-mixed-content-warning` - Enabled
- `#legacy-tls-enforced` - Enabled

**Comment by wchen342** [comment]
I applied the flags on v81, what I got was:
* On an `http` site, omnibox will display a grey triangle with `!`. Only if the triangle is tapped it will show a red crossed out `http://`.
* On a mixed content site, the omnibox will show a circle with `!` in the middle. When it is touched a notice saying mixed content will show.

I searched for the flag you mentioned in bromite/bromite#193, but there is no such flag. Do you have any idea on how to make the warnings explicit (e.g. no need to tap)?

**Comment by wchen342** [comment]
Ah I see the point, so with the default setting:
* On an `http` site it will display a circle with `!` in the middle
* On a mixed content site it will display nothing but starts with `https://`

Is this what you are saying with 

> the https display is inconsistent

?

**Comment by Madis0** [comment]
No, 

> the https display is inconsistent

because

> on host-only sites it's black, with a path it's green, with a colored background it's gray

but I suggested the flags because

> it [the protocol] doesn't give the full picture (e.g. broken https, localhost http) unlike the security state icon

so it would make sense to make the security icon state more "scary" where needed, as Google is aiming for it anyway.

Basically, the goal is

* https - no icon (no flag by Google yet though) 
* http, mixed https, old https - warning icon or warning page (Google is working on it, hence the flags)

**Comment by wchen342** [comment]
So i made some screenshots from my phone:

![all](https://user-images.githubusercontent.com/6406743/82978300-c168ad00-9fd3-11ea-96cf-398501ea02fd.jpg)

Left is flags off, right is flags on. `http` on top, mixed-contents in the middle, `https` at the bottom.

It seems to me the if the url is long then the protocal cannot be seen anyway. The difference is mainly in the icons displayed, which in the case of mixed-contents is changed most obviously. In the case of `http`, since the icon is not red I am not sure how useful is it actually.

Still I think I will accept the change since there is no harm, but I kind of feel these flags doesn't _actually solve_ the problem you mentioned.

**Comment by Madis0** [comment]
Well, I still suggested eliding the protocol too. 

The problem is simple - people have taught to read "https" so they put too much trust in it (mixed content, reading https instead of domain for verification etc). Same goes for padlock.

So the Google's idea is to remove any kind of indication from secure sites (padlock, protocol, green color) and mark them as "normal", while the insecure sites get increasingly bold warnings. This page illustrates the progress done for it: https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure

**Comment by wchen342** [comment]
I was trying to say that the flags doesn't actually remove the protocals (see the screenshots), only change the icons at the leftside. So are you suggesting me to edit out the protocal part natively?

**Comment by Madis0** [comment]
Yeah, there must be some other patch that made the protocols shown in this browser, as vanilla Chromium doesn't. Make sure www is still shown though!

**Comment by wchen342** [comment]
Ok I found the patch that changed this behavior. I believe this topic is worth further discussions in the main repo so I am going to make an issue there first and see their explanation of including the patch in the first place. At the mean time I will change the flags in the next version.

**Comment by wchen342** [comment]
The flags are changed in ff3bc4a. The `ungoogled-chromium` patch will be removed once the change lands in chromium.

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/21](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/21)
