### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by TotalCaesar659** [wchen342/ungoogled-chromium-android#22]
[NewPipe](https://github.com/TeamNewPipe/NewPipe) has update notification which downloads new version from github when pressing on it. It would be good to implement it in ungoogled-chromium.
![0](https://user-images.githubusercontent.com/14265316/82739554-0b8a2e00-9d49-11ea-8244-50b981d0ccd4.png)

**Comment by wchen342** [comment]
This can probably be done by modifying the existing update service of chromium, but I cannot say how feasible before seeing the code. Will take a look when I have time.

**Comment by Madis0** [comment]
How about a custom F-droid repo like Bromite does? So updates could be managed by F-droid.

**Comment by TotalCaesar659** [comment]
There is already F-Droid repo: https://github.com/wchen342/ungoogled-chromium-android#f-droid-repository
But it supports only arm64 architecture and can't be used on many old phones. Besides, it's easier for many people just to install APK without any repo.

**Comment by wchen342** [comment]
Yeah I can only upload one version of apk because of some weird f-droid server tool problem (if I put two apks with the same package name they will overwrite each other). I should probably upload `arm` builds instead in the future for better compatibility though.

**Comment by philS1** [comment]
Fdroid Repo seems to be down

**Comment by philS1** [comment]
@wchen342: you could create a new app called ungoogled-chromium64 for the arm64 version

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/22](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/22)
