### ISSUE TITLE
storage detection issue

### ISSUE THREAD

**Issue by eklavya002** [wchen342/ungoogled-chromium-android#23]
whenever i tried to download something browser throws error "SD CARD NOT FOUND" , this is the known chromium 81 issue but there is a patch available in bromite.
Device - pixel 2 xl
Rom stock android 10
![Screenshot_20200525-070801](https://user-images.githubusercontent.com/61374684/82770653-e552b400-9e56-11ea-9391-dfde9af32305.png)

**Comment by wchen342** [comment]
Should be gone with  ff3bc4a.
