### ISSUE TITLE
Text reflow?

### ISSUE THREAD

**Issue by Wacek** [wchen342/ungoogled-chromium-android#24]
Kiwi browser does have text reflow, (well sort of, since it sometimes results in right half of the page actually missing from the screen after reflowing) but most of the time it works and is very useful imho. I am trying to migrate somewhere, since Kiwi seems to be dead by now, and I have found your browser. Would you consider implementing it?

**Comment by wchen342** [comment]
Please fill out the request template first.
Are you saying you want text wrap on non-mobile pages?

**Comment by Wacek** [comment]
0k, I will paste it here:
**Is your feature request fall into the scope of ungoogled-chromium?**
Yes I think so, since It makes browsing easier, tapping on the text does not always fits it well on the screen

**Please describe the feature you would like to have**
Tex reflow witch pinch to zoom

**Describe the solution you'd like**
I would like this to happen at least on mobile pages similar to the way Kiwi does it

**Describe alternatives you've considered**
Opera of course, but I would like to stop using proprietary browsers

**Additional context**
Many people say, that text reflow on non mobile pages is a no go, so any form of text reflowin would be ok

**Comment by wchen342** [comment]
I am not sure I understand this:

- If the page is a mobile page, then the texts should be wrapped around already, otherwise there is some problem with the website itself.
- If it is non-mobile site, then as you mentioned it is hard to do because it requires modification of the rendering engine itself.

Do you have any example how this works, e.g. screenshot?

**Comment by hjyoung1** [comment]
Here's gif showing this in action. 
![20200531_142846](https://user-images.githubusercontent.com/45882061/83348526-1ba69c80-a34b-11ea-83c3-f8fbd022d1cf.gif)

**Comment by wchen342** [comment]
I see. This is more like a UI functionality IMO and does not really fall into the scope of this project. Unless there is an implication of privacy or transparency here then please explain further.
