### ISSUE TITLE
chrome://extensions is not accessible

### ISSUE THREAD

**Issue by KenMizz** [wchen342/ungoogled-chromium-android#28]
**Device info (please complete the following information):**
 - Device: Oneplus 7 Pro
 - OS: Oxygen OS 10
 - Arch: arm64
 - Variant: MonoChrome
 - Version:  83.0.4103.61-1

**Can the bug be reproduced with corresponding Chromium version?**
Yes

**Describe the bug**
chrome://extensions is not accessible

**To Reproduce**
1. Type in chrome://extensions in url bar

**Expected behavior**
Open up extensions page

**Screenshots**

![](https://i.loli.net/2020/06/01/k3HjLGDXTxP67nU.jpg)
**Additional context**

I'm using the latest build
But it didn't open the extensions page :/

**Comment by wchen342** [comment]
Can you show me your `chrome://chrome-urls`?

**Comment by eklavya002** [comment]
> Can you show me your `chrome://chrome-urls`?

May be he is using monochrome arm 64 build not extension specific build.

**Comment by KenMizz** [comment]
> > Can you show me your `chrome://chrome-urls`?
> 
> May be he is using monochrome arm 64 build not extension specific build.

So the arm64 one does not apply the extensions feature?

**Comment by Daplugg23** [comment]
> * Variant: MonoChrome
> * Version:  83.0.4103.61-1

You have the wrong version you need Extensions_ChromePublic_arm.apk

**Comment by wchen342** [comment]
Yeah that's what I suspected. I built only `chrome_arm` version with extension for maximum compatibility. You need to download the one starts with `Extensions_`.

**Comment by KenMizz** [comment]
Alright, thanks
