### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by vipinaggar** [wchen342/ungoogled-chromium-android#29]
![Screenshot_2020-06-01-11-24-00](https://user-images.githubusercontent.com/65840891/83380198-fbceb180-a3fa-11ea-9316-9a80d534ac7c.png)
![Screenshot_2020-06-01-11-23-54](https://user-images.githubusercontent.com/65840891/83380208-ff623880-a3fa-11ea-902e-c75974496df4.png)
extension not working android oreo

**Comment by wchen342** [comment]
Please fill out the issue template first and provide more information/logs.

**Comment by vipinaggar** [comment]
> Please fill out the issue template first and provide more information/logs.

**Device info (please complete the following information):**
 - Device: [lg q6]
 - OS: [oreo 8.1]
 - Arch: [arm]
 - Variant: [extension_chromepublic_arm]
 - Version: [83]

**Comment by rodrigoswz** [comment]
uBlock has always been known to not work very well in Kiwi, so here it must be the same.

Try the Nano Blocker, it is a fork of uBlock that works best on mobile. I tried it and worked for me on Ungoogled Chromium.

**Comment by wchen342** [comment]
I am not sure where to start investigating this though. I think it is related to the different between web content between desktop and mobile but this is not easy to solve.

**Comment by eklavya002** [comment]
> I am not sure where to start investigating this though. I think it is related to the different between web content between desktop and mobile but this is not easy to solve.

It seems there is some problem with ads filtering,i installed nano adblocker in kiwi and ungoogled chromium ,subscribed same filters but ungoogled chromium shows some pop ads on 9xmovies.cloud

**Comment by wchen342** [comment]
@eklavya002 If you use the debug apk in the other issue and open the webpage, is there any error shown in log?

**Comment by eklavya002** [comment]
> @eklavya002 If you use the debug apk in the other issue and open the webpage, is there any error shown in log?

i am not confirmed ,is it this?

06-02 00:20:34.356  5225  5225 I browser.browser: type=1400 audit(0.0:11155): avc: denied { open } for path="/proc/vmstat" dev="proc" ino=4026532173 scontext=u:r:untrusted_app_27:s0:c31,c257,c512,c768 tcontext=u:object_r:proc_vmstat:s0 tclass=file permissive=1
06-02 00:20:34.356  5225  5225 I browser.browser: type=1400 audit(0.0:11156): avc: denied { getattr } for path="/proc/vmstat" dev="proc" ino=4026532173 scontext=u:r:untrusted_app_27:s0:c31,c257,c512,c768 tcontext=u:object_r:proc_vmstat:s0 tclass=file permissive=1

**Comment by wchen342** [comment]
No these are unrelated. Look for something starts with `chromium:`, `ActivityManager:` or `cr_`.

**Comment by eklavya002** [comment]
> @eklavya002 If you use the debug apk in the other issue and open the webpage, is there any error shown in log?

yes confirmed above logs after every time i open a webpage

**Comment by eklavya002** [comment]
> chromium:

06-02 00:24:18.392  1275  1332 I ActivityManager: Start proc 26884:org.ungoogled.chromium.extensions:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:6/u0ai6 for  {org.ungoogled.chromium.extensions/org.chromium.content.app.SandboxedProcessService0:6}

**Comment by eklavya002** [comment]
> No these are unrelated. Look for something starts with `chromium:`, `ActivityManager:` or `cr_`.

06-02 00:24:18.493 26884 26884 I ocessService0:: Late-enabling -Xcheck:jni
06-02 00:24:18.521 26884 26884 E ocessService0:: Unknown bits set in runtime_flags: 0x8000
06-02 00:24:18.697 26884 26884 D cr_LibraryLoader: [LibraryLoader.java:213] Configuration, useChromiumLinker = false, useModernLinker = false
06-02 00:24:18.703 26884 26884 I cr_ChildProcessService: Creating new ChildProcessService pid=26884
06-02 00:24:18.712 24956 25044 D cr_ChildProcLauncher: [ChildProcessLauncher.java:231] on connect callback, pid=26884
06-02 00:24:18.729 26884 26904 I chromium: [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
06-02 00:24:18.729 26884 26904 I cr_LibraryLoader: Loaded native library version number "83.0.4103.61"

**Comment by wchen342** [comment]
Nothing there..Probably this doesn't trigger an error but fails in some other ways. I will try to investigate this on my own machine.

**Comment by eklavya002** [comment]
> Nothing there..Probably this doesn't trigger an error but fails in some other ways. I will try to investigate this on my own machine.

Is it possible there is something that blocks background processes of extensions?

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/29](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/29)
