### ISSUE TITLE
Installing ungoogled chromium for android is too complicated for most users and could be improved

### ISSUE THREAD

**Issue by BullShark** [wchen342/ungoogled-chromium-android#31]
Installing ungoogled chromium for android is too complicated. A user must find it on github, look under releases, and know which apks to download and which ones not to download when there's about 10 different apks. Not everyone knows what arm, arm64 or x86 means. This belongs on F-Droid with other open source free software so that users can easily install ungoogled chromium for android and also easily update it and be notified when there's an update available. This is especially important if a security fix is released and the update urgently needs to be installed.

https://f-droid.org/

https://f-droid.org/en/contribute/

**Submit Applications**
If you see an application missing from the repository (after reading the inclusion policy), please feel free to submit it via the dedicated Requests For Packaging issue tracker.

If you have the technical skills required, you can also put together the relevant metadata and submit that via the F-Droid Data repository, which will drastically speed up the inclusion of the application.

The same applies for helping to build newer versions of applications.

Further information can be found in the documentation, or by asking on IRC (#fdroid on freenode).

**Comment by wchen342** [comment]
The reason this is not in official f-droid repository is because of their inclusion policy. Bromite and other chromium variants have faced the similiar problems before.
The problems with inclusion policies are namely (qouting from [https://f-droid.org/en/docs/Inclusion_Policy/](https://f-droid.org/en/docs/Inclusion_Policy/):
> * We cannot build apps requiring Non-Free buildtools, including Oracle’s JDK or some pre-release toolchains.
> * Binary dependencies such as JAR files have to be replaced by source-built versions or used from a trusted repository

In addition, building chromium requires a lot of resources and additional set-ups, which is very hard to put into their docker-based server solution. There were unsuccessful attempts before (see #1).

**Comment by DragoCubed** [comment]
I'm a total noob and found it fairly easy. A few years ago I just Googled what architecture my device was and learnt about it.

An explanation could be added to the readme that mentions that devices can have different architectures and that phones typically have arm64 processors now and that downloads can be found on the releases page. It should also mention that monochrome only works from versions 7-9 as the readme currently says this: 
>MonoChromePublic is for API > 24 (Android 7.0) and contains both the browser and the webview. 

It could also mention that when you try to install it Android will warn you about apps from external sources. On Android 7 and below it is a system wide toggle and on some devices you can allow just the one installation. On Android 8 and above, it's per-app and it could be advised that the user disable the permission for their current browser. Google Play Protect will also give you a warning

The Bromite wiki and this: https://github.com/chromium/chromium/blob/2e2270c5e32dcde90c8bef265767bad645558c32/android_webview/docs/aosp-system-integration.md#trichrome are pretty helpful too.

so um. that's some stuff that I think would be useful.

**Comment by Madis0** [comment]
Perhaps make a [Github Page like Bromite](https://bromite.org)? I presume the selections are set there automatically once a release has been made.

**Comment by wchen342** [comment]
Probably, but making website is not exactly what I know. Maybe I can ask @csagan5 whether I can just adapt his codes for the Bromite site?

**Comment by csagan5** [comment]
@wchen342 sure, just keep some attribution in the files (a comment). The Bromite home page automatically selects the correct APK for the visitor, via Javascript.

**Comment by wchen342** [comment]
@csagan5 Ok no problem.

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/31](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/31)
