### ISSUE TITLE
Manage search engines

### ISSUE THREAD

**Issue by TotalCaesar659** [wchen342/ungoogled-chromium-android#34]
**Please describe the feature you would like to have**
An option to add/edit/remove search engines. Ungoogled-chromium on Android doesn't have it now.
![0](https://user-images.githubusercontent.com/14265316/83951339-75bacc80-a839-11ea-8b4c-ccb8b04f1b64.png)

**Is your feature request fall into the scope of ungoogled-chromium?**
This option is already in desktop ungoogled-chromium.
![1](https://user-images.githubusercontent.com/14265316/83951325-663b8380-a839-11ea-9427-9f0fb1fbefda.png)

**Describe alternatives you've considered**
Firefox Preview on Android has this option too.
![2](https://user-images.githubusercontent.com/14265316/83951322-5d4ab200-a839-11ea-9a9a-f6a89da6be8e.png)

**Comment by wchen342** [comment]
So you only want an option to delete a search engine? Because you can add one by search with it once.

**Comment by TotalCaesar659** [comment]
Why "Delete" only? "Add" (new button in search engines menu, as showed on screenshots, for adding without any searching), "Edit" (for existing ones) and "Delete".

**Comment by wchen342** [comment]
Well because that will mean making a complete new UI which will take time, so it's better if there is a simpler solution.

**Comment by Madis0** [comment]
As long as "recently visited" search engines work, it should be good enough already for the sake of maintainability (as, unlike desktop, the engine won't persist if you don't select it). Screenshot from Chrome:
![](https://i.imgur.com/9mjCR4w.jpg)

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/34](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/34)
