### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by wchen342** [wchen342/ungoogled-chromium-android#35]
I think at this point the to-do list is getting a little long for me so I should probably pin an issue that list the priority of tasks.

I will split these tasks into 3 categories: `core functionality`, `extensions` and `UI/UX`. As a general rule of thumb, core functionality will always take high priority.

Currently all tasks are assigned to me, but if anyone want to contribute please reply below so I can assign tasks.

Here is the list of currently ongoing things, ordered by priority from high to low:
1. [Core] #22: Update notification
5. [Core] #26: Bookmark all tabs and import/export bookmarks
6. [Extensions] Add remove prompt for extensions
7. [Extensions] #33: Show extension items in the menu
8. [UI/UX] #34: Manage search engines
8. [Extensions] Allow installation of extensions from webstore
9. [Extensions] #29: Some extension not working

**Comment by Madis0** [comment]
FYI, Github has the feature [Projects](https://github.com/wchen342/ungoogled-chromium-android/projects) for this.

**Comment by wchen342** [comment]
@Madis0 Ah didn't know that. Thanks for mentioning it.

**Comment by wchen342** [comment]
Closing in preferance of [Projects](https://github.com/wchen342/ungoogled-chromium-android/projects/1).
