### ISSUE TITLE
Add remove prompt for extensions

### ISSUE THREAD

**Issue by Madis0** [wchen342/ungoogled-chromium-android#36]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
Extensions should be uninstallable.

**Please describe the feature you would like to have**
The remove button in extensions page should prompt the user whether they want to remove an extension or not.

**Describe the solution you'd like**
1. Click Remove under an extension
2. User is asked, whether they want to remove the extension
3. When tapped yes, extension is removed

**Describe alternatives you've considered**
N/A

**Additional context**
#35

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/36](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/36)
