### ISSUE TITLE
Allow installation of extensions from webstore

### ISSUE THREAD

**Issue by Madis0** [wchen342/ungoogled-chromium-android#37]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
Extensions are hard to install at the moment, it would be nice if the web store install button was directly available.

**Please describe the feature you would like to have**
- [ ] Force desktop UA for Chrome Web Store
- [ ] Prompt for extension install when clicking the install button

**Describe the solution you'd like**
Desktop UA is necessary to avoid the "send to desktop" stuff Google has, prompt is needed for easier installation.

**Describe alternatives you've considered**
[The bookmarklet](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#downloading-the-crx-file) could be bundled in the app as a bookmark, so that the user could just type "Add extension" or such to the omnibox when on an extension page.

**Additional context**
#35

**Comment by wchen342** [comment]
AFAIK forcing UA is not enough to let webstore recognize the browser as crhome/chromium. Most likely as mentioned in [#8](https://github.com/wchen342/ungoogled-chromium-android/issues/8#issuecomment-640292093) it will be some kind of API.

Two solutions exists: one is using a flag to control whether the API should be activated, or using an addon that helps downloading extensions.

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/37](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/37)
