### ISSUE TITLE
missed  '#enable-process-sharing-with-strict-site-instances'  flag of ram using. feature.

### ISSUE THREAD

**Issue by DI555** [wchen342/ungoogled-chromium-android#41]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
See [ungoogled-chromium#objectives](https://github.com/Eloston/ungoogled-chromium#objectives) for a detailed list of objectives of this project. [...]

**Please describe the feature you would like to have**
A clear and concise description of what the problem is. [...]

#enable-process-sharing-with-strict-site-instances

i miss it in the recent chromium versions, i suppose the big g deleted it((. but it was very useful , especially for those who have a lots of using pages - not to letting get each page one process in ram.
this flag was let to use the ram better, it combined multiple 'tabs'
 to less processes in ram. 
the description was:

Process sharing with strict site instances
When site isolation is disabled, this mode changes how sites are lumped in to a shared process. Process selection is usually controlled with site instances. With strict site isolation, each site on a page gets its own site instance and process. With site isolation disabled and without this mode, all sites that share a process are put into the same site instance. This mode adds a third way: site instances are strictly separated like strict site isolation, but process selection puts multiple site instances in a single process. – Android

is it possible to get this flag back?

**Comment by wchen342** [comment]
Did this flag exist on desktop too? Process isolation sounds like a desktop feature. Also I think I read somewhere in Vanadium doc that chromium never had true isolation like firefox does.
If they removed the isolation codes then I won't be able to fix this, but I will try to find when and how they removed the flag.

**Comment by DI555** [comment]
i saw a word '- Android' in the end of description..., so it's an Android specific one imo....
but if it could be ported to Desktop version either it would be great !
this flag is about isolation but with lot less processes in ram for that..., so in Desktop version it will be highly usefull too!

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/41](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/41)
