### ISSUE TITLE
External Download Manager Support

### ISSUE THREAD

**Issue by Raul1198** [wchen342/ungoogled-chromium-android#42]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
 Because it add more feature in Download

**Please describe the feature you would like to have**
Support for external download manager like ADM,Navi Download, uGet ..etc

**Describe the solution you'd like**
When downloading any file the Download redirect to the selected download managerso that the selected Download manager save the files in a different folder like zip in compressed , media in video and so on.

**Describe alternatives you've considered**
External Download manager support is available in Kiwi
Browser

**Additional context**
![Screenshot_20200610-220706873](https://user-images.githubusercontent.com/29801315/84294414-c21e4900-ab66-11ea-9ff2-d64654f4ba4a.jpg)

**Comment by wchen342** [comment]
I don't see how this fits in the goal of ungoogled-chromium. Please explain.

**Comment by DI555** [comment]
there is exist integration already. just long-tap on link, pick send/share and choose one downloader.
after that the icon of that downloader will be near send/share long-tap menu.

**Comment by Raul1198** [comment]
> I don't see how this fits in the goal of ungoogled-chromium. Please explain.

i mean this would come handy when downloading large file as sometimes it so happen that after adding a file to download the the download stop or get slow

**Comment by wchen342** [comment]
The native downloading tool doesn't send data to Google AFAIK so there is no privacy implication. If your point is purely on a convinience basis then it is beyond the scope of the project.
Also as @DI555 said there is another way to send downloads to third-party download managers.

**Comment by Raul1198** [comment]
thats a fair point, i was just suggesting thought it might be useful 🙂 😅
