### ISSUE TITLE
Moving off github

### ISSUE THREAD

**Issue by wchen342** [wchen342/ungoogled-chromium-android#43]
I am planning to move the repo off Github, probably to a self hosted instance. I will try to keep pushing to the mirror, preferably in an automated way, at [ungoogled-software/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android).

Is that cool with you? @Eloston

**Comment by Eloston** [comment]
Works for me!

**Comment by DI555** [comment]
gitlab?

**Comment by wchen342** [comment]
> gitlab?

No I am working on moving to a self-hosting Gitea instance under the same domain of my f-droid repo (droidware.info). You will still be able to post issues to [ungoogled-software/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android), I will check there.

**Comment by wchen342** [comment]
This repo has been migrated to [https://git.droidware.info/wchen342/ungoogled-chromium-android](https://git.droidware.info/wchen342/ungoogled-chromium-android). It will soon be archived.

Old issues will keep being tracked in the new repo, and new issues should either be opened at [ungoogled-software/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android) or [https://git.droidware.info/wchen342/ungoogled-chromium-android](https://git.droidware.info/wchen342/ungoogled-chromium-android).
