### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by rongpengli** [wchen342/ungoogled-chromium-android#44]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S8]
 - OS: [e.g. Android 9, SM-9500 Build/PPR1.180610]
 - Arch: [e.g. arm]
 - Variant: [e.g. extension]
 - Version: [e.g. 83.0.4103]
 
**\*Is the bug related to extensions/on the extension-support version?**
Yes

**\*Describe the bug**

**\*To Reproduce**
1. Go to 'chrome://extensions'
2. Turn on "Developer Mode"
3. Load the unzipped extensions
4. No extensions are loaded with an error "未能成功加载扩展程序 清单文件缺失或不可读取"

The other way to install extension by downloading app does not work, either.

**\*Expected behavior**
The extension is enabled.

**Comment by wchen342** [comment]
Please post the adb log when you are loading the extension.

**Comment by rongpengli** [comment]
Can you tell how to get the log?

> Please post the adb log when you are loading the extension.

**Comment by wchen342** [comment]
Here are some tutorials:

- [https://forum.xda-developers.com/showthread.php?t=1726238](https://forum.xda-developers.com/showthread.php?t=1726238)
- [https://www.xda-developers.com/how-to-take-logs-in-android/](https://www.xda-developers.com/how-to-take-logs-in-android/)
- [https://forum.xda-developers.com/showthread.php?t=2303834](https://forum.xda-developers.com/showthread.php?t=2303834)

**Comment by DI555** [comment]
i got not handling installation of extensions either((
flag   #extension-mime-request-handling   is  set to 'Always prompt for install' , but just get progress downloading  of .crx file and saving it((
i tried it with downloading from github with .crx file.

imo the key  #extension-mime-request-handling is broken/not_works((.

**Comment by wchen342** [comment]
@DI555 Your problem is probably different from OP's. I discovered I hardcoded the way `crx` file is opened to be compatible with Android 10 and now it is incompatible with lower versions. I will fix this in next version.

**Comment by rongpengli** [comment]
@wchen342 Just come here to say I can install the extensions on the version 83.0.4103.106 now.
