### ISSUE TITLE
Some Requests as a Impressed User:

### ISSUE THREAD

**Issue by 1923-u** [wchen342/ungoogled-chromium-android#45]

**Comment by 1923-u** [comment]
Sorry for writing here, but https://github.com/bromite/bromite/issues/520 dont allow me to comment as me being a new user.
@SebiderSushi
@linuxandria
@csagan5
Editing framework-res is no longer required as:
Note: Please read Complete especially reddit.com
Important: https://www.reddit.com/r/LineageOS/comments/ffnpgu/what_was_the_reason_of_moving_webview_apk_from/ 
InShort: https://www.reddit.com/r/LineageOS/comments/ffnpgu/comment/fjzq2yg 
Background: 
1: https://www.androidpolice.com/2019/10/24/android-10-no-longer-uses-chrome-app-to-render-pages-inside-apps/
2: https://www.xda-developers.com/google-chrome-no-longer-webview-provider-android-10/
------------------------------------------------------------------------------------------------------------------
TWRP: 
https://github.com/TeamWin/twrpmeUse a stub/(i use)placeholder application inside it's flashable.zip recovery image which they say is done to workaround the space/size limitations on the recovery partition and important to note is that after updating from the PlayStore it acts like a normal System Application because the placeholder application was placed in /system/app/.

**Comment by 1923-u** [comment]
I think that You and @csagan5 can establish a partnership for a common website and F-Droid repository rather than working seperatly.

**Comment by wchen342** [comment]
Can you please copy the issue to [ungoogled-chromium/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android) so we can continue discuss there? I will archive this repo very soon.

Also although it is only me that is maintaining this repo at this time, but it is still part of `ungoogled-chromium`, and we have [different objectives](https://github.com/Eloston/ungoogled-chromium#objectives) than `Bromite`.

**Comment by 1923-u** [comment]
> Can you please copy the issue to [ungoogled-chromium/ungoogled-chromium-android](https://github.com/ungoogled-software/ungoogled-chromium-android) so we can continue the discussion there? I will archive this repo very soon.
> 
> Also although it is only me that is maintaining this repo at this time, but it is still part of `ungoogled-chromium`, and we have [different objectives](https://github.com/Eloston/ungoogled-chromium#objectives) than `Bromite`.

Sorry, 
May i ask how?

**Comment by wchen342** [comment]
Just copy paste everything you posted.

**Comment by 1923-u** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-android/issues/19 
Done Sir
