### ISSUE TITLE
Add to ungoogled-software

### ISSUE THREAD

**Issue by wchen342** [wchen342/ungoogled-chromium-android#6]
@Eloston I wonder whether the current status of this repo is good enough to be added to `ungoogled-software`, can you comment?

Here is a summary of what I have done so far:

- Built with libre rebuild of Android SDK/NDK.
- Removed binary dependencies in build tools except for one (desugar-runtime.jar from bazel. I haven't figure out how to build it but will do later.)
- Removed all Google Play Service libraries.
- There are still google libraries remains, but they are either open-sourced (like Guava) or with disabled functionalities (ar, vr, etc.).

The current build is not tested throughly enough though, so there may be hidden bugs, but I think adding it to `ungoogled-software` and also README of `ungoogled-chromium` will gain it more focus which can help debugging.

**Comment by Eloston** [comment]
I can tell you've spent quite a bit of time on this, and are continually looking for ways to improve things. You're an ideal contributor; great work!

You probably already saw this, but I've added you to a new team (android) and forked your repo: https://github.com/ungoogled-software/ungoogled-chromium-android. Right now, you should have full access to the forked repo and the team. I haven't used GitHub teams/organizations in a while, so let me know if there's something I should tweak.

**Comment by wchen342** [comment]
Thanks for the kind words. I have never used the organization before so I need to see how to use it. What do you think is the best way to update the forked repo? What is in my head right now is

- I do any work in my repo
- I create a pull request to the forked repo whenever there is a new version
- You or I approve the pull request

, sounds good?

**Comment by Eloston** [comment]
Yeah, that sounds good to me. It doesn't actually matter too much since you're the only contributor right now, but your proposal is more formal.
