### ISSUE TITLE
Add button to create new folder in bookmarks

### ISSUE THREAD

**Issue by TotalCaesar659** [wchen342/ungoogled-chromium-android#9]
There are no button to create new folder in bookmarks, just search and close.
![0](https://user-images.githubusercontent.com/14265316/66237622-32ceb500-e6fe-11e9-9c24-de22f254bce7.png)
The only way for it is: to open a web site, add the bookmark for it and edit with creating new folder.
![1](https://user-images.githubusercontent.com/14265316/66237634-382bff80-e6fe-11e9-940e-c40f79e84d61.png)
[Firefox Preview](https://github.com/mozilla-mobile/fenix) has this button.
![2](https://user-images.githubusercontent.com/14265316/66237655-45e18500-e6fe-11e9-85ec-47eff9deac79.png)
Please, add this button to bookmarks, it would be more comfortable for creating folders there.

**Comment by wchen342** [comment]
I had a look at this part of the codes and discovered that the `add folder` function is deeply coupled with editing a bookmark (i.e. the functions creating the selection/new folder activities requires at least one selected bookmark to work). I can probably make it work if there is at least one existing bookmark and so I can make the button select the first bookmark automatically, but I doubt that will be any more convenient than its current state?

**Comment by TotalCaesar659** [comment]
Then could you ask Chromium developers to do it? I don't understand why they hadn't thought about it.

**Comment by wchen342** [comment]
Added in https://github.com/wchen342/ungoogled-chromium-android/commit/c0b185845bf00ff75430a90dfc03f28c9e3584fe.
